# Generated by Django 4.0.2 on 2022-02-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=True, upload_to='pics'),
        ),
    ]
