# Generated by Django 4.0.2 on 2022-02-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_cart', '0002_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
